## Problem Statement:

#### Predict Loan Eligibility for Dream Housing Finance company
#### Dream Housing Finance company deals in all kinds of home loans. They have presence across all urban, semi urban and rural areas. Customer first applies for home loan and after that company validates the customer eligibility for loan.

#### Company wants to automate the loan eligibility process (real time) based on customer detail provided while filling online application form. These details are Gender, Marital Status, Education, Number of Dependents, Income, Loan Amount, Credit History and others. To automate this process, they have provided a dataset to identify the customers segments that are eligible for loan amount so that they can specifically target these customers.

### Library:

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

### Data Gathering:

In [2]:
train_data = pd.read_csv(r'D:\Datascience\inceptez\Preprocessing\Loan Predictions\train_ctrUa4K.csv')
test_data = pd.read_csv(r'D:\Datascience\inceptez\Preprocessing\Loan Predictions\test_lAUu6dG.csv')
sample_data = pd.read_csv(r'D:\Datascience\inceptez\Preprocessing\Loan Predictions\sample_submission_49d68Cx.csv')

In [3]:
train_data.shape

(614, 13)

In [4]:
test_data.shape

(367, 12)

### Feature Engineering:

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [7]:
train_data.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [8]:
train_data.duplicated().sum()

0

In [9]:
train_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Loan_ID,614,614,LP001002,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,601,2,Male,489,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Married,611,2,Yes,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,599,4,0,345,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education,614,2,Graduate,480,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Self_Employed,582,2,No,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ApplicantIncome,614.0,NaN,NaN,NaN,5403.459283,6109.041673,150.0,2877.5,3812.5,5795.0,81000.0
CoapplicantIncome,614.0,NaN,NaN,NaN,1621.245798,2926.248369,0.0,0.0,1188.5,2297.25,41667.0
LoanAmount,592.0,NaN,NaN,NaN,146.412162,85.587325,9.0,100.0,128.0,168.0,700.0
Loan_Amount_Term,600.0,NaN,NaN,NaN,342.0,65.12041,12.0,360.0,360.0,360.0,480.0
Credit_History,564.0,NaN,NaN,NaN,0.842199,0.364878,0.0,1.0,1.0,1.0,1.0
Property_Area,614,3,Semiurban,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Loan_Status,614,2,Y,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
train_data[train_data['Loan_Status']=='N']

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,LP002943,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [11]:
pd.set_option('display.max_rows', 500)
train_data[train_data['Loan_Status']=='N']

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
30,LP001091,Male,Yes,1,Graduate,NaN,4166,3369.0,201.0,360.0,NaN,Urban,N
31,LP001095,Male,No,0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban,N
32,LP001097,Male,No,1,Graduate,Yes,4692,0.0,106.0,360.0,1.0,Rural,N
34,LP001100,Male,No,3+,Graduate,No,12500,3000.0,320.0,360.0,1.0,Rural,N
36,LP001109,Male,Yes,0,Graduate,No,1828,1330.0,100.0,NaN,0.0,Urban,N
40,LP001119,Male,No,0,Graduate,No,3600,0.0,80.0,360.0,1.0,Urban,N
48,LP001146,Female,Yes,0,Graduate,No,2645,3440.0,120.0,360.0,0.0,Urban,N
52,LP001164,Female,No,0,Graduate,No,4230,0.0,112.0,360.0,1.0,Semiurban,N
53,LP001179,Male,Yes,2,Graduate,No,4616,0.0,134.0,360.0,1.0,Urban,N
54,LP001186,Female,Yes,1,Graduate,Yes,11500,0.0,286.0,360.0,0.0,Urban,N
57,LP001197,Male,Yes,0,Graduate,No,3366,2200.0,135.0,360.0,1.0,Rural,N
62,LP001207,Male,Yes,0,Not Graduate,Yes,2609,3449.0,165.0,180.0,0.0,Rural,N
63,LP001213,Male,Yes,1,Graduate,No,4945,0.0,NaN,360.0,0.0,Rural,N
64,LP001222,Female,No,0,Graduate,No,4166,0.0,116.0,360.0,0.0,Semiurban,N
65,LP001225,Male,Yes,0,Graduate,No,5726,4595.0,258.0,360.0,1.0,Semiurban,N
66,LP001228,Male,No,0,Not Graduate,No,3200,2254.0,126.0,180.0,0.0,Urban,N
69,LP001241,Female,No,0,Graduate,No,4300,0.0,136.0,360.0,0.0,Semiurban,N
73,LP001250,Male,Yes,3+,Not Graduate,No,4755,0.0,95.0,NaN,0.0,Semiurban,N
75,LP001255,Male,No,0,Graduate,No,3750,0.0,113.0,480.0,1.0,Urban,N
76,LP001256,Male,No,0,Graduate,No,3750,4750.0,176.0,360.0,1.0,Urban,N
77,LP001259,Male,Yes,1,Graduate,Yes,1000,3022.0,110.0,360.0,1.0,Urban,N
78,LP001263,Male,Yes,3+,Graduate,No,3167,4000.0,180.0,300.0,0.0,Semiurban,N
82,LP001267,Female,Yes,2,Graduate,No,1378,1881.0,167.0,360.0,1.0,Urban,N
83,LP001273,Male,Yes,0,Graduate,No,6000,2250.0,265.0,360.0,NaN,Semiurban,N
95,LP001326,Male,No,0,Graduate,NaN,6782,0.0,NaN,360.0,NaN,Urban,N
107,LP001370,Male,No,0,Not Graduate,NaN,7333,0.0,120.0,360.0,1.0,Rural,N
108,LP001379,Male,Yes,2,Graduate,No,3800,3600.0,216.0,360.0,0.0,Urban,N
112,LP001391,Male,Yes,0,Not Graduate,No,3572,4114.0,152.0,NaN,0.0,Rural,N
118,LP001421,Male,Yes,0,Graduate,No,5568,2142.0,175.0,360.0,1.0,Rural,N
128,LP001451,Male,Yes,1,Graduate,Yes,10513,3850.0,160.0,180.0,0.0,Urban,N
129,LP001465,Male,Yes,0,Graduate,No,6080,2569.0,182.0,360.0,NaN,Rural,N
135,LP001488,Male,Yes,3+,Graduate,No,4000,7750.0,290.0,360.0,1.0,Semiurban,N
136,LP001489,Female,Yes,0,Graduate,No,4583,0.0,84.0,360.0,1.0,Rural,N
138,LP001492,Male,No,0,Graduate,No,14999,0.0,242.0,360.0,0.0,Semiurban,N
139,LP001493,Male,Yes,2,Not Graduate,No,4200,1430.0,129.0,360.0,1.0,Rural,N
140,LP001497,Male,Yes,2,Graduate,No,5042,2083.0,185.0,360.0,1.0,Rural,N
148,LP001519,Female,No,0,Graduate,No,10000,1666.0,225.0,360.0,1.0,Rural,N
150,LP001528,Male,No,0,Graduate,No,6277,0.0,118.0,360.0,0.0,Rural,N
152,LP001531,Male,No,0,Graduate,No,9166,0.0,244.0,360.0,1.0,Urban,N
153,LP001532,Male,Yes,2,Not Graduate,No,2281,0.0,113.0,360.0,1.0,Rural,N
161,LP001562,Male,Yes,0,Graduate,No,7933,0.0,275.0,360.0,1.0,Urban,N
162,LP001565,Male,Yes,1,Graduate,No,3089,1280.0,121.0,360.0,0.0,Semiurban,N
166,LP001577,Female,Yes,0,Graduate,No,4583,0.0,112.0,360.0,1.0,Rural,N
168,LP001579,Male,No,0,Graduate,No,2237,0.0,63.0,480.0,0.0,Semiurban,N
172,LP001586,Male,Yes,3+,Not Graduate,No,3522,0.0,81.0,180.0,1.0,Rural,N
174,LP001603,Male,Yes,0,Not Graduate,Yes,4344,736.0,87.0,360.0,1.0,Semiurban,N
177,LP001610,Male,Yes,3+,Graduate,No,5516,11300.0,495.0,360.0,0.0,Semiurban,N
179,LP001630,Male,No,0,Not Graduate,No,2333,1451.0,102.0,480.0,0.0,Urban,N
180,LP001633,Male,Yes,1,Graduate,No,6400,7250.0,180.0,360.0,0.0,Urban,N
181,LP001634,Male,No,0,Graduate,No,1916,5063.0,67.0,360.0,NaN,Rural,N
183,LP001637,Male,Yes,1,Graduate,No,33846,0.0,260.0,360.0,1.0,Semiurban,N
186,LP001641,Male,Yes,1,Graduate,Yes,2178,0.0,66.0,300.0,0.0,Rural,N
191,LP001656,Male,No,0,Graduate,No,12000,0.0,164.0,360.0,1.0,Semiurban,N
192,LP001657,Male,Yes,0,Not Graduate,No,6033,0.0,160.0,360.0,1.0,Urban,N
195,LP001665,Male,Yes,1,Graduate,No,3125,2583.0,170.0,360.0,1.0,Semiurban,N
199,LP001673,Male,No,0,Graduate,Yes,11000,0.0,83.0,360.0,1.0,Urban,N
202,LP001682,Male,Yes,3+,Not Graduate,No,3992,0.0,NaN,180.0,1.0,Urban,N
209,LP001702,Male,No,0,Graduate,No,3418,0.0,127.0,360.0,1.0,Semiurban,N
210,LP001708,Female,No,0,Graduate,No,10000,0.0,214.0,360.0,1.0,Semiurban,N
211,LP001711,Male,Yes,3+,Graduate,No,3430,1250.0,128.0,360.0,0.0,Semiurban,N
216,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
218,LP001732,Male,Yes,2,Graduate,NaN,5000,0.0,72.0,360.0,0.0,Semiurban,N
220,LP001736,Male,Yes,0,Graduate,No,2221,0.0,60.0,360.0,0.0,Urban,N
225,LP001751,Male,Yes,0,Graduate,No,3250,0.0,170.0,360.0,1.0,Rural,N
226,LP001754,Male,Yes,NaN,Not Graduate,Yes,4735,0.0,138.0,360.0,1.0,Urban,N
236,LP001786,Male,Yes,0,Graduate,NaN,5746,0.0,255.0,360.0,NaN,Urban,N
241,LP001800,Male,Yes,1,Not Graduate,No,2510,1983.0,140.0,180.0,1.0,Urban,N
245,LP001813,Male,No,0,Graduate,Yes,6050,4333.0,120.0,180.0,1.0,Urban,N
250,LP001835,Male,Yes,0,Not Graduate,No,1668,3890.0,201.0,360.0,0.0,Semiurban,N
251,LP001836,Female,No,2,Graduate,No,3427,0.0,138.0,360.0,1.0,Urban,N
254,LP001844,Male,No,0,Graduate,Yes,16250,0.0,192.0,360.0,0.0,Urban,N
256,LP001849,Male,No,0,Not Graduate,No,6045,0.0,115.0,360.0,0.0,Rural,N
257,LP001854,Male,Yes,3+,Graduate,No,5250,0.0,94.0,360.0,1.0,Urban,N
258,LP001859,Male,Yes,0,Graduate,No,14683,2100.0,304.0,360.0,1.0,Rural,N
259,LP001864,Male,Yes,3+,Not Graduate,No,4931,0.0,128.0,360.0,NaN,Semiurban,N
262,LP001870,Female,No,1,Graduate,No,3481,0.0,155.0,36.0,1.0,Semiurban,N
268,LP001883,Female,No,0,Graduate,NaN,3418,0.0,135.0,360.0,1.0,Rural,N
280,LP001910,Male,No,1,Not Graduate,Yes,4053,2426.0,158.0,360.0,0.0,Urban,N
284,LP001922,Male,Yes,0,Graduate,No,20667,0.0,NaN,360.0,1.0,Rural,N
286,LP001925,Female,No,0,Graduate,Yes,2600,1717.0,99.0,300.0,1.0,Semiurban,N
291,LP001938,Male,Yes,2,Graduate,No,4400,0.0,127.0,360.0,0.0,Semiurban,N
293,LP001945,Female,No,NaN,Graduate,No,5417,0.0,143.0,480.0,0.0,Urban,N
298,LP001955,Female,No,0,Graduate,No,5000,2541.0,151.0,480.0,1.0,Rural,N
299,LP001963,Male,Yes,1,Graduate,No,2014,2925.0,113.0,360.0,1.0,Urban,N
300,LP001964,Male,Yes,0,Not Graduate,No,1800,2934.0,93.0,360.0,0.0,Urban,N
305,LP001990,Male,No,0,Not Graduate,No,2000,0.0,NaN,360.0,1.0,Urban,N
307,LP001994,Female,No,0,Graduate,No,2400,1863.0,104.0,360.0,0.0,Urban,N
308,LP001996,Male,No,0,Graduate,No,20233,0.0,480.0,360.0,1.0,Rural,N
314,LP002024,NaN,Yes,0,Graduate,No,2473,1843.0,159.0,360.0,1.0,Rural,N
319,LP002050,Male,Yes,1,Graduate,Yes,10000,0.0,155.0,360.0,1.0,Rural,N
325,LP002067,Male,Yes,1,Graduate,Yes,8666,4983.0,376.0,360.0,0.0,Rural,N
328,LP002086,Female,Yes,0,Graduate,No,4333,2451.0,110.0,360.0,1.0,Urban,N
338,LP002113,Female,No,3+,Not Graduate,No,1830,0.0,NaN,360.0,0.0,Urban,N
340,LP002115,Male,Yes,3+,Not Graduate,No,2647,1587.0,173.0,360.0,1.0,Rural,N
341,LP002116,Female,No,0,Graduate,No,2378,0.0,46.0,360.0,1.0,Rural,N
346,LP002130,Male,Yes,NaN,Not Graduate,No,3523,3230.0,152.0,360.0,0.0,Rural,N
351,LP002140,Male,No,0,Graduate,No,8750,4167.0,308.0,360.0,1.0,Rural,N
353,LP002142,Female,Yes,0,Graduate,Yes,5500,0.0,105.0,360.0,0.0,Rural,N
357,LP002151,Male,Yes,1,Graduate,No,3875,0.0,67.0,360.0,1.0,Urban,N
358,LP002158,Male,Yes,0,Not Graduate,No,3000,1666.0,100.0,480.0,0.0,Urban,N
360,LP002161,Female,No,1,Graduate,No,4723,0.0,81.0,360.0,1.0,Semiurban,N
365,LP002181,Male,No,0,Not Graduate,No,6216,0.0,133.0,360.0,1.0,Rural,N
366,LP002187,Male,No,0,Graduate,No,2500,0.0,96.0,480.0,1.0,Semiurban,N
367,LP002188,Male,No,0,Graduate,No,5124,0.0,124.0,NaN,0.0,Rural,N
369,LP002191,Male,Yes,0,Graduate,No,19730,5266.0,570.0,360.0,1.0,Rural,N
373,LP002205,Male,No,1,Graduate,No,3062,1987.0,111.0,180.0,0.0,Urban,N
378,LP002224,Male,No,0,Graduate,No,3069,0.0,71.0,480.0,1.0,Urban,N
384,LP002236,Male,Yes,2,Graduate,No,4566,0.0,100.0,360.0,1.0,Urban,N
387,LP002243,Male,Yes,0,Not Graduate,No,3010,3136.0,NaN,360.0,0.0,Urban,N
396,LP002277,Female,No,0,Graduate,No,3180,0.0,71.0,360.0,0.0,Urban,N
399,LP002287,Female,No,0,Graduate,No,1500,1800.0,103.0,360.0,0.0,Semiurban,N
400,LP002288,Male,Yes,2,Not Graduate,No,2889,0.0,45.0,180.0,0.0,Urban,N
401,LP002296,Male,No,0,Not Graduate,No,2755,0.0,65.0,300.0,1.0,Rural,N
404,LP002301,Female,No,0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural,N
408,LP002315,Male,Yes,1,Graduate,No,8300,0.0,152.0,300.0,0.0,Semiurban,N
409,LP002317,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural,N
410,LP002318,Female,No,1,Not Graduate,Yes,3867,0.0,62.0,360.0,1.0,Semiurban,N
412,LP002328,Male,Yes,0,Not Graduate,No,6096,0.0,218.0,360.0,0.0,Rural,N
414,LP002335,Female,Yes,0,Not Graduate,No,2149,3237.0,178.0,360.0,0.0,Semiurban,N
416,LP002341,Female,No,1,Graduate,No,2600,0.0,160.0,360.0,1.0,Urban,N
417,LP002342,Male,Yes,2,Graduate,Yes,1600,20000.0,239.0,360.0,1.0,Urban,N
421,LP002357,Female,No,0,Not Graduate,No,2720,0.0,80.0,NaN,0.0,Urban,N
423,LP002362,Male,Yes,1,Graduate,No,7250,1667.0,110.0,NaN,0.0,Urban,N
426,LP002367,Female,No,1,Not Graduate,No,4606,0.0,81.0,360.0,1.0,Rural,N
431,LP002379,Male,No,0,Graduate,No,6500,0.0,105.0,360.0,0.0,Rural,N
438,LP002403,Male,No,0,Graduate,Yes,10416,0.0,187.0,360.0,0.0,Urban,N
447,LP002435,Male,Yes,0,Graduate,NaN,3539,1376.0,55.0,360.0,1.0,Rural,N
448,LP002443,Male,Yes,2,Graduate,No,3340,1710.0,150.0,360.0,0.0,Rural,N
449,LP002444,Male,No,1,Not Graduate,Yes,2769,1542.0,190.0,360.0,NaN,Semiurban,N
450,LP002446,Male,Yes,2,Not Graduate,No,2309,1255.0,125.0,360.0,0.0,Rural,N
452,LP002448,Male,Yes,0,Graduate,No,3948,1733.0,149.0,360.0,0.0,Rural,N
457,LP002467,Male,Yes,0,Graduate,No,3708,2569.0,173.0,360.0,1.0,Urban,N
459,LP002473,Male,Yes,0,Graduate,No,8334,0.0,160.0,360.0,1.0,Semiurban,N
464,LP002493,Male,No,0,Graduate,No,4166,0.0,98.0,360.0,0.0,Semiurban,N
466,LP002500,Male,Yes,3+,Not Graduate,No,2947,1664.0,70.0,180.0,0.0,Urban,N
469,LP002505,Male,Yes,0,Graduate,No,4333,2451.0,110.0,360.0,1.0,Urban,N
471,LP002517,Male,Yes,1,Not Graduate,No,2653,1500.0,113.0,180.0,0.0,Rural,N
477,LP002530,NaN,Yes,2,Graduate,No,2873,1872.0,132.0,360.0,0.0,Semiurban,N
479,LP002533,Male,Yes,2,Graduate,No,2947,1603.0,NaN,360.0,1.0,Urban,N
486,LP002545,Male,No,2,Graduate,No,3547,0.0,80.0,360.0,0.0,Rural,N
487,LP002547,Male,Yes,1,Graduate,No,18333,0.0,500.0,360.0,1.0,Urban,N
489,LP002556,Male,No,0,Graduate,No,2435,0.0,75.0,360.0,1.0,Urban,N
494,LP002585,Male,Yes,0,Graduate,No,3597,2157.0,119.0,360.0,0.0,Rural,N
499,LP002602,Male,No,0,Graduate,No,6283,4416.0,209.0,360.0,0.0,Rural,N
503,LP002618,Male,Yes,1,Not Graduate,No,4050,5302.0,138.0,360.0,NaN,Rural,N
507,LP002625,NaN,No,0,Graduate,No,3583,0.0,96.0,360.0,1.0,Urban,N
510,LP002637,Male,No,0,Not Graduate,No,3598,1287.0,100.0,360.0,1.0,Rural,N
513,LP002648,Male,Yes,0,Graduate,No,2130,6666.0,70.0,180.0,1.0,Semiurban,N
514,LP002652,Male,No,0,Graduate,No,5815,3666.0,311.0,360.0,1.0,Rural,N
517,LP002682,Male,Yes,NaN,Not Graduate,No,3074,1800.0,123.0,360.0,0.0,Semiurban,N
518,LP002683,Male,No,0,Graduate,No,4683,1915.0,185.0,360.0,1.0,Semiurban,N
519,LP002684,Female,No,0,Not Graduate,No,3400,0.0,95.0,360.0,1.0,Rural,N
524,LP002697,Male,No,0,Graduate,No,4680,2087.0,NaN,360.0,1.0,Semiurban,N
532,LP002723,Male,No,2,Graduate,No,3588,0.0,110.0,360.0,0.0,Rural,N
533,LP002729,Male,No,1,Graduate,No,11250,0.0,196.0,360.0,NaN,Semiurban,N
538,LP002739,Male,Yes,0,Not Graduate,No,2917,536.0,66.0,360.0,1.0,Rural,N
541,LP002743,Female,No,0,Graduate,No,2138,0.0,99.0,360.0,0.0,Semiurban,N
546,LP002768,Male,No,0,Not Graduate,No,3358,0.0,80.0,36.0,1.0,Semiurban,N
548,LP002776,Female,No,0,Graduate,No,5000,0.0,103.0,360.0,0.0,Semiurban,N
550,LP002778,Male,Yes,2,Graduate,Yes,6633,0.0,NaN,360.0,0.0,Rural,N
553,LP002788,Male,Yes,0,Not Graduate,No,2454,2333.0,181.0,360.0,0.0,Urban,N
554,LP002789,Male,Yes,0,Graduate,No,3593,4266.0,132.0,180.0,0.0,Rural,N
564,LP002832,Male,Yes,2,Graduate,No,8799,0.0,258.0,360.0,0.0,Urban,N
567,LP002837,Male,Yes,3+,Graduate,No,3400,2500.0,123.0,360.0,0.0,Rural,N
568,LP002840,Female,No,0,Graduate,No,2378,0.0,9.0,360.0,1.0,Urban,N
569,LP002841,Male,Yes,0,Graduate,No,3166,2064.0,104.0,360.0,0.0,Urban,N
571,LP002847,Male,Yes,NaN,Graduate,No,5116,1451.0,165.0,360.0,0.0,Urban,N
573,LP002862,Male,Yes,2,Not Graduate,No,6125,1625.0,187.0,480.0,1.0,Semiurban,N
574,LP002863,Male,Yes,3+,Graduate,No,6406,0.0,150.0,360.0,1.0,Semiurban,N
576,LP002872,NaN,Yes,0,Graduate,No,3087,2210.0,136.0,360.0,0.0,Semiurban,N
581,LP002893,Male,No,0,Graduate,No,1836,33837.0,90.0,360.0,1.0,Urban,N
583,LP002898,Male,Yes,1,Graduate,No,1880,0.0,61.0,360.0,NaN,Rural,N
584,LP002911,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural,N
585,LP002912,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural,N
589,LP002926,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
591,LP002931,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,N
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,LP002943,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [12]:
train_data[train_data['Loan_Status']=='N'].describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Loan_ID,192,192,LP001003,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,187,2,Male,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Married,192,2,Yes,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,186,4,0,107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education,192,2,Graduate,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Self_Employed,183,2,No,157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ApplicantIncome,192.0,NaN,NaN,NaN,5446.078125,6819.558528,150.0,2885.0,3833.5,5861.25,81000.0
CoapplicantIncome,192.0,NaN,NaN,NaN,1877.807292,4384.060103,0.0,0.0,268.0,2273.75,41667.0
LoanAmount,181.0,NaN,NaN,NaN,151.220994,85.862783,9.0,100.0,129.0,176.0,570.0
Loan_Amount_Term,186.0,NaN,NaN,NaN,344.064516,69.238921,36.0,360.0,360.0,360.0,480.0
Credit_History,179.0,NaN,NaN,NaN,0.541899,0.499639,0.0,0.0,1.0,1.0,1.0
Property_Area,192,3,Rural,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Loan_Status,192,1,N,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
train_data[train_data['Loan_Status']=='Y']

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.000000,NaN,360.0,1.0,Urban,Y
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.000000,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.000000,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.000000,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.000000,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.000000,95.0,360.0,1.0,Urban,Y
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.000000,168.0,360.0,1.0,Urban,Y
10,LP001024,Male,Yes,2,Graduate,No,3200,700.000000,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.000000,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.000000,200.0,360.0,1.0,Urban,Y
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.000000,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.000000,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.000000,100.0,240.0,NaN,Urban,Y
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.000000,115.0,NaN,1.0,Urban,Y
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.000000,315.0,360.0,1.0,Urban,Y
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.000000,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.000000,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.000000,110.0,360.0,1.0,Urban,Y
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.000000,120.0,360.0,1.0,Semiurban,Y
33,LP001098,Male,Yes,0,Graduate,No,3500,1667.000000,114.0,360.0,1.0,Semiurban,Y
35,LP001106,Male,Yes,0,Graduate,No,2275,2067.000000,NaN,360.0,1.0,Urban,Y
37,LP001112,Female,Yes,0,Graduate,No,3667,1459.000000,144.0,360.0,1.0,Semiurban,Y
38,LP001114,Male,No,0,Graduate,No,4166,7210.000000,184.0,360.0,1.0,Urban,Y
39,LP001116,Male,No,0,Not Graduate,No,3748,1668.000000,110.0,360.0,1.0,Semiurban,Y
41,LP001120,Male,No,0,Graduate,No,1800,1213.000000,47.0,360.0,1.0,Urban,Y
42,LP001123,Male,Yes,0,Graduate,No,2400,0.000000,75.0,360.0,NaN,Urban,Y
43,LP001131,Male,Yes,0,Graduate,No,3941,2336.000000,134.0,360.0,1.0,Semiurban,Y
44,LP001136,Male,Yes,0,Not Graduate,Yes,4695,0.000000,96.0,NaN,1.0,Urban,Y
45,LP001137,Female,No,0,Graduate,No,3410,0.000000,88.0,NaN,1.0,Urban,Y
46,LP001138,Male,Yes,1,Graduate,No,5649,0.000000,44.0,360.0,1.0,Urban,Y
47,LP001144,Male,Yes,0,Graduate,No,5821,0.000000,144.0,360.0,1.0,Urban,Y
49,LP001151,Female,No,0,Graduate,No,4000,2275.000000,144.0,360.0,1.0,Semiurban,Y
50,LP001155,Female,Yes,0,Not Graduate,No,1928,1644.000000,100.0,360.0,1.0,Semiurban,Y
51,LP001157,Female,No,0,Graduate,No,3086,0.000000,120.0,360.0,1.0,Semiurban,Y
55,LP001194,Male,Yes,2,Graduate,No,2708,1167.000000,97.0,360.0,1.0,Semiurban,Y
56,LP001195,Male,Yes,0,Graduate,No,2132,1591.000000,96.0,360.0,1.0,Semiurban,Y
58,LP001198,Male,Yes,1,Graduate,No,8080,2250.000000,180.0,360.0,1.0,Urban,Y
59,LP001199,Male,Yes,2,Not Graduate,No,3357,2859.000000,144.0,360.0,1.0,Urban,Y
60,LP001205,Male,Yes,0,Graduate,No,2500,3796.000000,120.0,360.0,1.0,Urban,Y
61,LP001206,Male,Yes,3+,Graduate,No,3029,0.000000,99.0,360.0,1.0,Urban,Y
67,LP001233,Male,Yes,1,Graduate,No,10750,0.000000,312.0,360.0,1.0,Urban,Y
68,LP001238,Male,Yes,3+,Not Graduate,Yes,7100,0.000000,125.0,60.0,1.0,Urban,Y
70,LP001243,Male,Yes,0,Graduate,No,3208,3066.000000,172.0,360.0,1.0,Urban,Y
71,LP001245,Male,Yes,2,Not Graduate,Yes,1875,1875.000000,97.0,360.0,1.0,Semiurban,Y
72,LP001248,Male,No,0,Graduate,No,3500,0.000000,81.0,300.0,1.0,Semiurban,Y
74,LP001253,Male,Yes,3+,Graduate,Yes,5266,1774.000000,187.0,360.0,1.0,Semiurban,Y
79,LP001264,Male,Yes,3+,Not Graduate,Yes,3333,2166.000000,130.0,360.0,NaN,Semiurban,Y
80,LP001265,Female,No,0,Graduate,No,3846,0.000000,111.0,360.0,1.0,Semiurban,Y
81,LP001266,Male,Yes,1,Graduate,Yes,2395,0.000000,NaN,360.0,1.0,Semiurban,Y
84,LP001275,Male,Yes,1,Graduate,No,3988,0.000000,50.0,240.0,1.0,Urban,Y
85,LP001279,Male,No,0,Graduate,No,2366,2531.000000,136.0,360.0,1.0,Semiurban,Y
86,LP001280,Male,Yes,2,Not Graduate,No,3333,2000.000000,99.0,360.0,NaN,Semiurban,Y
87,LP001282,Male,Yes,0,Graduate,No,2500,2118.000000,104.0,360.0,1.0,Semiurban,Y
88,LP001289,Male,No,0,Graduate,No,8566,0.000000,210.0,360.0,1.0,Urban,Y
89,LP001310,Male,Yes,0,Graduate,No,5695,4167.000000,175.0,360.0,1.0,Semiurban,Y
90,LP001316,Male,Yes,0,Graduate,No,2958,2900.000000,131.0,360.0,1.0,Semiurban,Y
91,LP001318,Male,Yes,2,Graduate,No,6250,5654.000000,188.0,180.0,1.0,Semiurban,Y
92,LP001319,Male,Yes,2,Not Graduate,No,3273,1820.000000,81.0,360.0,1.0,Urban,Y
93,LP001322,Male,No,0,Graduate,No,4133,0.000000,122.0,360.0,1.0,Semiurban,Y
94,LP001325,Male,No,0,Not Graduate,No,3620,0.000000,25.0,120.0,1.0,Semiurban,Y
96,LP001327,Female,Yes,0,Graduate,No,2484,2302.000000,137.0,360.0,1.0,Semiurban,Y
97,LP001333,Male,Yes,0,Graduate,No,1977,997.000000,50.0,360.0,1.0,Semiurban,Y
98,LP001334,Male,Yes,0,Not Graduate,No,4188,0.000000,115.0,180.0,1.0,Semiurban,Y
99,LP001343,Male,Yes,0,Graduate,No,1759,3541.000000,131.0,360.0,1.0,Semiurban,Y
100,LP001345,Male,Yes,2,Not Graduate,No,4288,3263.000000,133.0,180.0,1.0,Urban,Y
101,LP001349,Male,No,0,Graduate,No,4843,3806.000000,151.0,360.0,1.0,Semiurban,Y
102,LP001350,Male,Yes,NaN,Graduate,No,13650,0.000000,NaN,360.0,1.0,Urban,Y
103,LP001356,Male,Yes,0,Graduate,No,4652,3583.000000,NaN,360.0,1.0,Semiurban,Y
104,LP001357,Male,NaN,NaN,Graduate,No,3816,754.000000,160.0,360.0,1.0,Urban,Y
105,LP001367,Male,Yes,1,Graduate,No,3052,1030.000000,100.0,360.0,1.0,Urban,Y
106,LP001369,Male,Yes,2,Graduate,No,11417,1126.000000,225.0,360.0,1.0,Urban,Y
109,LP001384,Male,Yes,3+,Not Graduate,No,2071,754.000000,94.0,480.0,1.0,Semiurban,Y
110,LP001385,Male,No,0,Graduate,No,5316,0.000000,136.0,360.0,1.0,Urban,Y
111,LP001387,Female,Yes,0,Graduate,NaN,2929,2333.000000,139.0,360.0,1.0,Semiurban,Y
113,LP001392,Female,No,1,Graduate,Yes,7451,0.000000,NaN,360.0,1.0,Semiurban,Y
114,LP001398,Male,No,0,Graduate,NaN,5050,0.000000,118.0,360.0,1.0,Semiurban,Y
115,LP001401,Male,Yes,1,Graduate,No,14583,0.000000,185.0,180.0,1.0,Rural,Y
116,LP001404,Female,Yes,0,Graduate,No,3167,2283.000000,154.0,360.0,1.0,Semiurban,Y
117,LP001405,Male,Yes,1,Graduate,No,2214,1398.000000,85.0,360.0,NaN,Urban,Y
119,LP001422,Female,No,0,Graduate,No,10408,0.000000,259.0,360.0,1.0,Urban,Y
120,LP001426,Male,Yes,NaN,Graduate,No,5667,2667.000000,180.0,360.0,1.0,Rural,Y
121,LP001430,Female,No,0,Graduate,No,4166,0.000000,44.0,360.0,1.0,Semiurban,Y
122,LP001431,Female,No,0,Graduate,No,2137,8980.000000,137.0,360.0,0.0,Semiurban,Y
123,LP001432,Male,Yes,2,Graduate,No,2957,0.000000,81.0,360.0,1.0,Semiurban,Y
124,LP001439,Male,Yes,0,Not Graduate,No,4300,2014.000000,194.0,360.0,1.0,Rural,Y
125,LP001443,Female,No,0,Graduate,No,3692,0.000000,93.0,360.0,NaN,Rural,Y
126,LP001448,NaN,Yes,3+,Graduate,No,23803,0.000000,370.0,360.0,1.0,Rural,Y
127,LP001449,Male,No,0,Graduate,No,3865,1640.000000,NaN,360.0,1.0,Rural,Y
130,LP001469,Male,No,0,Graduate,Yes,20166,0.000000,650.0,480.0,NaN,Urban,Y
131,LP001473,Male,No,0,Graduate,No,2014,1929.000000,74.0,360.0,1.0,Urban,Y
132,LP001478,Male,No,0,Graduate,No,2718,0.000000,70.0,360.0,1.0,Semiurban,Y
133,LP001482,Male,Yes,0,Graduate,Yes,3459,0.000000,25.0,120.0,1.0,Semiurban,Y
134,LP001487,Male,No,0,Graduate,No,4895,0.000000,102.0,360.0,1.0,Semiurban,Y
137,LP001491,Male,Yes,2,Graduate,Yes,3316,3500.000000,88.0,360.0,1.0,Urban,Y
141,LP001498,Male,No,0,Graduate,No,5417,0.000000,168.0,360.0,1.0,Urban,Y
142,LP001504,Male,No,0,Graduate,Yes,6950,0.000000,175.0,180.0,1.0,Semiurban,Y
143,LP001507,Male,Yes,0,Graduate,No,2698,2034.000000,122.0,360.0,1.0,Semiurban,Y
144,LP001508,Male,Yes,2,Graduate,No,11757,0.000000,187.0,180.0,1.0,Urban,Y
145,LP001514,Female,Yes,0,Graduate,No,2330,4486.000000,100.0,360.0,1.0,Semiurban,Y
146,LP001516,Female,Yes,2,Graduate,No,14866,0.000000,70.0,360.0,1.0,Urban,Y
147,LP001518,Male,Yes,1,Graduate,No,1538,1425.000000,30.0,360.0,1.0,Urban,Y
149,LP001520,Male,Yes,0,Graduate,No,4860,830.000000,125.0,360.0,1.0,Semiurban,Y
151,LP001529,Male,Yes,0,Graduate,Yes,2577,3750.000000,152.0,360.0,1.0,Rural,Y
154,LP001535,Male,No,0,Graduate,No,3254,0.000000,50.0,360.0,1.0,Urban,Y
155,LP001536,Male,Yes,3+,Graduate,No,39999,0.000000,600.0,180.0,0.0,Semiurban,Y
156,LP001541,Male,Yes,1,Graduate,No,6000,0.000000,160.0,360.0,NaN,Rural,Y
157,LP001543,Male,Yes,1,Graduate,No,9538,0.000000,187.0,360.0,1.0,Urban,Y
158,LP001546,Male,No,0,Graduate,NaN,2980,2083.000000,120.0,360.0,1.0,Rural,Y
159,LP001552,Male,Yes,0,Graduate,No,4583,5625.000000,255.0,360.0,1.0,Semiurban,Y
160,LP001560,Male,Yes,0,Not Graduate,No,1863,1041.000000,98.0,360.0,1.0,Semiurban,Y
163,LP001570,Male,Yes,2,Graduate,No,4167,1447.000000,158.0,360.0,1.0,Rural,Y
164,LP001572,Male,Yes,0,Graduate,No,9323,0.000000,75.0,180.0,1.0,Urban,Y
165,LP001574,Male,Yes,0,Graduate,No,3707,3166.000000,182.0,NaN,1.0,Rural,Y
167,LP001578,Male,Yes,0,Graduate,No,2439,3333.000000,129.0,360.0,1.0,Rural,Y
169,LP001580,Male,Yes,2,Graduate,No,8000,0.000000,200.0,360.0,1.0,Semiurban,Y
170,LP001581,Male,Yes,0,Not Graduate,NaN,1820,1769.000000,95.0,360.0,1.0,Rural,Y
171,LP001585,NaN,Yes,3+,Graduate,No,51763,0.000000,700.0,300.0,1.0,Urban,Y
173,LP001594,Male,Yes,0,Graduate,No,5708,5625.000000,187.0,360.0,1.0,Semiurban,Y
175,LP001606,Male,Yes,0,Graduate,No,3497,1964.000000,116.0,360.0,1.0,Rural,Y
176,LP001608,Male,Yes,2,Graduate,No,2045,1619.000000,101.0,360.0,1.0,Rural,Y
178,LP001616,Male,Yes,1,Graduate,No,3750,0.000000,116.0,360.0,1.0,Semiurban,Y
182,LP001636,Male,Yes,0,Graduate,No,4600,0.000000,73.0,180.0,1.0,Semiurban,Y
184,LP001639,Female,Yes,0,Graduate,No,3625,0.000000,108.0,360.0,1.0,Semiurban,Y
185,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.000000,120.0,360.0,1.0,Semiurban,Y
187,LP001643,Male,Yes,0,Graduate,No,2383,2138.000000,58.0,360.0,NaN,Rural,Y
188,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.000000,168.0,360.0,1.0,Rural,Y
189,LP001647,Male,Yes,0,Graduate,No,9328,0.000000,188.0,180.0,1.0,Rural,Y
190,LP001653,Male,No,0,Not Graduate,No,4885,0.000000,48.0,360.0,1.0,Rural,Y
193,LP001658,Male,No,0,Graduate,No,3858,0.000000,76.0,360.0,1.0,Semiurban,Y
194,LP001664,Male,No,0,Graduate,No,4191,0.000000,120.0,360.0,1.0,Rural,Y
196,LP001666,Male,No,0,Graduate,No,8333,3750.000000,187.0,360.0,1.0,Rural,Y
197,LP001669,Female,No,0,Not Graduate,No,1907,2365.000000,120.0,NaN,1.0,Urban,Y
198,LP001671,Female,Yes,0,Graduate,No,3416,2816.000000,113.0,360.0,NaN,Semiurban,Y
200,LP001674,Male,Yes,1,Not Graduate,No,2600,2500.000000,90.0,360.0,1.0,Semiurban,Y
201,LP001677,Male,No,2,Graduate,No,4923,0.000000,166.0,360.0,0.0,Semiurban,Y
203,LP001688,Male,Yes,1,Not Graduate,No,3500,1083.000000,135.0,360.0,1.0,Urban,Y
204,LP001691,Male,Yes,2,Not Graduate,No,3917,0.000000,124.0,360.0,1.0,Semiurban,Y
205,LP001692,Female,No,0,Not Graduate,No,4408,0.000000,120.0,360.0,1.0,Semiurban,Y
206,LP001693,Female,No,0,Graduate,No,3244,0.000000,80.0,360.0,1.0,Urban,Y
207,LP001698,Male,No,0,Not Graduate,No,3975,2531.000000,55.0,360.0,1.0,Rural,Y
208,LP001699,Male,No,0,Graduate,No,2479,0.000000,59.0,360.0,1.0,Urban,Y
212,LP001713,Male,Yes,1,Graduate,Yes,7787,0.000000,240.0,360.0,1.0,Urban,Y
213,LP001715,Male,Yes,3+,Not Graduate,Yes,5703,0.000000,130.0,360.0,1.0,Rural,Y
214,LP001716,Male,Yes,0,Graduate,No,3173,3021.000000,137.0,360.0,1.0,Urban,Y
215,LP001720,Male,Yes,3+,Not Graduate,No,3850,983.000000,100.0,360.0,1.0,Semiurban,Y
217,LP001726,Male,Yes,0,Graduate,No,3727,1775.000000,131.0,360.0,1.0,Semiurban,Y
219,LP001734,Female,Yes,2,Graduate,No,4283,2383.000000,127.0,360.0,NaN,Semiurban,Y
221,LP001743,Male,Yes,2,Graduate,No,4009,1717.000000,116.0,360.0,1.0,Semiurban,Y
222,LP001744,Male,No,0,Graduate,No,2971,2791.000000,144.0,360.0,1.0,Semiurban,Y
223,LP001749,Male,Yes,0,Graduate,No,7578,1010.000000,175.0,NaN,1.0,Semiurban,Y
224,LP001750,Male,Yes,0,Graduate,No,6250,0.000000,128.0,360.0,1.0,Semiurban,Y
227,LP001758,Male,Yes,2,Graduate,No,6250,1695.000000,210.0,360.0,1.0,Semiurban,Y
228,LP001760,Male,NaN,NaN,Graduate,No,4758,0.000000,158.0,480.0,1.0,Semiurban,Y
229,LP001761,Male,No,0,Graduate,Yes,6400,0.000000,200.0,360.0,1.0,Rural,Y
230,LP001765,Male,Yes,1,Graduate,No,2491,2054.000000,104.0,360.0,1.0,Semiurban,Y
231,LP001768,Male,Yes,0,Graduate,NaN,3716,0.000000,42.0,180.0,1.0,Rural,Y
232,LP001770,Male,No,0,Not Graduate,No,3189,2598.000000,120.0,NaN,1.0,Rural,Y
233,LP001776,Female,No,0,Graduate,No,8333,0.000000,280.0,360.0,1.0,Semiurban,Y
234,LP001778,Male,Yes,1,Graduate,No,3155,1779.000000,140.0,360.0,1.0,Semiurban,Y
235,LP001784,Male,Yes,1,Graduate,No,5500,1260.000000,170.0,360.0,1.0,Rural,Y
237,LP001788,Female,No,0,Graduate,Yes,3463,0.000000,122.0,360.0,NaN,Urban,Y
238,LP001790,Female,No,1,Graduate,No,3812,0.000000,112.0,360.0,1.0,Rural,Y
239,LP001792,Male,Yes,1,Graduate,No,3315,0.000000,96.0,360.0,1.0,Semiurban,Y
240,LP001798,Male,Yes,2,Graduate,No,5819,5000.000000,120.0,360.0,1.0,Rural,Y
242,LP001806,Male,No,0,Graduate,No,2965,5701.000000,155.0,60.0,1.0,Urban,Y
243,LP001807,Male,Yes,2,Graduate,Yes,6250,1300.000000,108.0,360.0,1.0,Rural,Y
244,LP001811,Male,Yes,0,Not Graduate,No,3406,4417.000000,123.0,360.0,1.0,Semiurban,Y
246,LP001814,Male,Yes,2,Graduate,No,9703,0.000000,112.0,360.0,1.0,Urban,Y
247,LP001819,Male,Yes,1,Not Graduate,No,6608,0.000000,137.0,180.0,1.0,Urban,Y
248,LP001824,Male,Yes,1,Graduate,No,2882,1843.000000,123.0,480.0,1.0,Semiurban,Y
249,LP001825,Male,Yes,0,Graduate,No,1809,1868.000000,90.0,360.0,1.0,Urban,Y
252,LP001841,Male,No,0,Not Graduate,Yes,2583,2167.000000,104.0,360.0,1.0,Rural,Y
253,LP001843,Male,Yes,1,Not Graduate,No,2661,7101.000000,279.0,180.0,1.0,Semiurban,Y
255,LP001846,Female,No,3+,Graduate,No,3083,0.000000,255.0,360.0,1.0,Rural,Y
260,LP001865,Male,Yes,1,Graduate,No,6083,4250.000000,330.0,360.0,NaN,Urban,Y
261,LP001868,Male,No,0,Graduate,No,2060,2209.000000,134.0,360.0,1.0,Semiurban,Y
263,LP001871,Female,No,0,Graduate,No,7200,0.000000,120.0,360.0,1.0,Rural,Y
264,LP001872,Male,No,0,Graduate,Yes,5166,0.000000,128.0,360.0,1.0,Semiurban,Y
265,LP001875,Male,No,0,Graduate,No,4095,3447.000000,151.0,360.0,1.0,Rural,Y
266,LP001877,Male,Yes,2,Graduate,No,4708,1387.000000,150.0,360.0,1.0,Semiurban,Y
267,LP001882,Male,Yes,3+,Graduate,No,4333,1811.000000,160.0,360.0,0.0,Urban,Y
269,LP001884,Female,No,1,Graduate,No,2876,1560.000000,90.0,360.0,1.0,Urban,Y
270,LP001888,Female,No,0,Graduate,No,3237,0.000000,30.0,360.0,1.0,Urban,Y
271,LP001891,Male,Yes,0,Graduate,No,11146,0.000000,136.0,360.0,1.0,Urban,Y
272,LP001892,Male,No,0,Graduate,No,2833,1857.000000,126.0,360.0,1.0,Rural,Y
273,LP001894,Male,Yes,0,Graduate,No,2620,2223.000000,150.0,360.0,1.0,Semiurban,Y
274,LP001896,Male,Yes,2,Graduate,No,3900,0.000000,90.0,360.0,1.0,Semiurban,Y
275,LP001900,Male,Yes,1,Graduate,No,2750,1842.000000,115.0,360.0,1.0,Semiurban,Y
276,LP001903,Male,Yes,0,Graduate,No,3993,3274.000000,207.0,360.0,1.0,Semiurban,Y
277,LP001904,Male,Yes,0,Graduate,No,3103,1300.000000,80.0,360.0,1.0,Urban,Y
278,LP001907,Male,Yes,0,Graduate,No,14583,0.000000,436.0,360.0,1.0,Semiurban,Y
279,LP001908,Female,Yes,0,Not Graduate,No,4100,0.000000,124.0,360.0,NaN,Rural,Y
281,LP001914,Male,Yes,0,Graduate,No,3927,800.000000,112.0,360.0,1.0,Semiurban,Y
282,LP001915,Male,Yes,2,Graduate,No,2301,985.799988,78.0,180.0,1.0,Urban,Y
283,LP001917,Female,No,0,Graduate,No,1811,1666.000000,54.0,360.0,1.0,Urban,Y
285,LP001924,Male,No,0,Graduate,No,3158,3053.000000,89.0,360.0,1.0,Rural,Y
287,LP001926,Male,Yes,0,Graduate,No,3704,2000.000000,120.0,360.0,1.0,Rural,Y
288,LP001931,Female,No,0,Graduate,No,4124,0.000000,115.0,360.0,1.0,Semiurban,Y
289,LP001935,Male,No,0,Graduate,No,9508,0.000000,187.0,360.0,1.0,Rural,Y
290,LP001936,Male,Yes,0,Graduate,No,3075,2416.000000,139.0,360.0,1.0,Rural,Y
292,LP001940,Male,Yes,2,Graduate,No,3153,1560.000000,134.0,360.0,1.0,Urban,Y
294,LP001947,Male,Yes,0,Graduate,No,2383,3334.000000,172.0,360.0,1.0,Semiurban,Y
295,LP001949,Male,Yes,3+,Graduate,NaN,4416,1250.000000,110.0,360.0,1.0,Urban,Y
296,LP001953,Male,Yes,1,Graduate,No,6875,0.000000,200.0,360.0,1.0,Semiurban,Y
297,LP001954,Female,Yes,1,Graduate,No,4666,0.000000,135.0,360.0,1.0,Urban,Y
301,LP001972,Male,Yes,NaN,Not Graduate,No,2875,1750.000000,105.0,360.0,1.0,Semiurban,Y
302,LP001974,Female,No,0,Graduate,No,5000,0.000000,132.0,360.0,1.0,Rural,Y
303,LP001977,Male,Yes,1,Graduate,No,1625,1803.000000,96.0,360.0,1.0,Urban,Y
304,LP001978,Male,No,0,Graduate,No,4000,2500.000000,140.0,360.0,1.0,Rural,Y
306,LP001993,Female,No,0,Graduate,No,3762,1666.000000,135.0,360.0,1.0,Rural,Y
309,LP001998,Male,Yes,2,Not Graduate,No,7667,0.000000,185.0,360.0,NaN,Rural,Y
310,LP002002,Female,No,0,Graduate,No,2917,0.000000,84.0,360.0,1.0,Semiurban,Y
311,LP002004,Male,No,0,Not Graduate,No,2927,2405.000000,111.0,360.0,1.0,Semiurban,Y
312,LP002006,Female,No,0,Graduate,No,2507,0.000000,56.0,360.0,1.0,Rural,Y
313,LP002008,Male,Yes,2,Graduate,Yes,5746,0.000000,144.0,84.0,NaN,Rural,Y
315,LP002031,Male,Yes,1,Not Graduate,No,3399,1640.000000,111.0,180.0,1.0,Urban,Y
316,LP002035,Male,Yes,2,Graduate,No,3717,0.000000,120.0,360.0,1.0,Semiurban,Y
317,LP002036,Male,Yes,0,Graduate,No,2058,2134.000000,88.0,360.0,NaN,Urban,Y
318,LP002043,Female,No,1,Graduate,No,3541,0.000000,112.0,360.0,NaN,Semiurban,Y
320,LP002051,Male,Yes,0,Graduate,No,2400,2167.000000,115.0,360.0,1.0,Semiurban,Y
321,LP002053,Male,Yes,3+,Graduate,No,4342,189.000000,124.0,360.0,1.0,Semiurban,Y
322,LP002054,Male,Yes,2,Not Graduate,No,3601,1590.000000,NaN,360.0,1.0,Rural,Y
323,LP002055,Female,No,0,Graduate,No,3166,2985.000000,132.0,360.0,NaN,Rural,Y
324,LP002065,Male,Yes,3+,Graduate,No,15000,0.000000,300.0,360.0,1.0,Rural,Y
326,LP002068,Male,No,0,Graduate,No,4917,0.000000,130.0,360.0,0.0,Rural,Y
327,LP002082,Male,Yes,0,Graduate,Yes,5818,2160.000000,184.0,360.0,1.0,Semiurban,Y
329,LP002087,Female,No,0,Graduate,No,2500,0.000000,67.0,360.0,1.0,Urban,Y
330,LP002097,Male,No,1,Graduate,No,4384,1793.000000,117.0,360.0,1.0,Urban,Y
331,LP002098,Male,No,0,Graduate,No,2935,0.000000,98.0,360.0,1.0,Semiurban,Y
332,LP002100,Male,No,NaN,Graduate,No,2833,0.000000,71.0,360.0,1.0,Urban,Y
333,LP002101,Male,Yes,0,Graduate,NaN,63337,0.000000,490.0,180.0,1.0,Urban,Y
334,LP002103,NaN,Yes,1,Graduate,Yes,9833,1833.000000,182.0,180.0,1.0,Urban,Y
335,LP002106,Male,Yes,NaN,Graduate,Yes,5503,4490.000000,70.0,NaN,1.0,Semiurban,Y
336,LP002110,Male,Yes,1,Graduate,NaN,5250,688.000000,160.0,360.0,1.0,Rural,Y
337,LP002112,Male,Yes,2,Graduate,Yes,2500,4600.000000,176.0,360.0,1.0,Rural,Y
339,LP002114,Female,No,0,Graduate,No,4160,0.000000,71.0,360.0,1.0,Semiurban,Y
342,LP002119,Male,Yes,1,Not Graduate,No,4554,1229.000000,158.0,360.0,1.0,Urban,Y
343,LP002126,Male,Yes,3+,Not Graduate,No,3173,0.000000,74.0,360.0,1.0,Semiurban,Y
344,LP002128,Male,Yes,2,Graduate,NaN,2583,2330.000000,125.0,360.0,1.0,Rural,Y
345,LP002129,Male,Yes,0,Graduate,No,2499,2458.000000,160.0,360.0,1.0,Semiurban,Y
347,LP002131,Male,Yes,2,Not Graduate,No,3083,2168.000000,126.0,360.0,1.0,Urban,Y
348,LP002137,Male,Yes,0,Graduate,No,6333,4583.000000,259.0,360.0,NaN,Semiurban,Y
349,LP002138,Male,Yes,0,Graduate,No,2625,6250.000000,187.0,360.0,1.0,Rural,Y
350,LP002139,Male,Yes,0,Graduate,No,9083,0.000000,228.0,360.0,1.0,Semiurban,Y
352,LP002141,Male,Yes,3+,Graduate,No,2666,2083.000000,95.0,360.0,1.0,Rural,Y
354,LP002143,Female,Yes,0,Graduate,No,2423,505.000000,130.0,360.0,1.0,Semiurban,Y
355,LP002144,Female,No,NaN,Graduate,No,3813,0.000000,116.0,180.0,1.0,Urban,Y
356,LP002149,Male,Yes,2,Graduate,No,8333,3167.000000,165.0,360.0,1.0,Rural,Y
359,LP002160,Male,Yes,3+,Graduate,No,5167,3167.000000,200.0,360.0,1.0,Semiurban,Y
361,LP002170,Male,Yes,2,Graduate,No,5000,3667.000000,236.0,360.0,1.0,Semiurban,Y
362,LP002175,Male,Yes,0,Graduate,No,4750,2333.000000,130.0,360.0,1.0,Urban,Y
363,LP002178,Male,Yes,0,Graduate,No,3013,3033.000000,95.0,300.0,NaN,Urban,Y
364,LP002180,Male,No,0,Graduate,Yes,6822,0.000000,141.0,360.0,1.0,Rural,Y
368,LP002190,Male,Yes,1,Graduate,No,6325,0.000000,175.0,360.0,1.0,Semiurban,Y

In [14]:
train_data[train_data['Loan_Status']=='Y'].describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Loan_ID,422,422,LP001002,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,414,2,Male,339,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Married,419,2,Yes,285,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,413,4,0,238,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education,422,2,Graduate,340,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Self_Employed,399,2,No,343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ApplicantIncome,422.0,NaN,NaN,NaN,5384.06872,5765.441615,210.0,2877.5,3812.5,5771.5,63337.0
CoapplicantIncome,422.0,NaN,NaN,NaN,1504.516398,1924.754855,0.0,0.0,1239.5,2297.25,20000.0
LoanAmount,411.0,NaN,NaN,NaN,144.294404,85.484607,17.0,100.0,126.0,161.0,700.0
Loan_Amount_Term,414.0,NaN,NaN,NaN,341.072464,63.24777,12.0,360.0,360.0,360.0,480.0
Credit_History,385.0,NaN,NaN,NaN,0.981818,0.133782,0.0,1.0,1.0,1.0,1.0
Property_Area,422,3,Semiurban,179,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Loan_Status,422,1,Y,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
train_data.groupby(['Loan_Status','Credit_History'])['Loan_Status'].count()

Loan_Status  Credit_History
N            0.0                82
             1.0                97
Y            0.0                 7
             1.0               378
Name: Loan_Status, dtype: int64

In [16]:
train_data.groupby(by=['Loan_Status','Credit_History']).count()

                            Loan_ID  Gender  Married  Dependents  Education  \
Loan_Status Credit_History
N           0.0                  82      79       82          77         82
            1.0                  97      95       97          96         97
Y           0.0                   7       7        7           7          7
            1.0                 378     371      375         369        378

                            Self_Employed  ApplicantIncome  CoapplicantIncome  \
Loan_Status Credit_History
N           0.0                        81               82                 82
            1.0                        94               97                 97
Y           0.0                         7                7                  7
            1.0                       356              378                378

                            LoanAmount  Loan_Amount_Term  Property_Area
Loan_Status Credit_History
N           0.0                     78                76             82
            1.0                     91                97             97
Y           0.0                      7                 7              7
            1.0                    367               370            378

In [17]:
#train_data[train_data['Loan_Status']=='N'].describe(include='all').T
train_data.groupby(by=['Loan_Status','Gender']).count()

                    Loan_ID  Married  Dependents  Education  Self_Employed  \
Loan_Status Gender
N           Female       37       37          36         37             35
            Male        150      150         145        150            143
Y           Female       75       74          73         75             69
            Male        339      337         332        339            322

                    ApplicantIncome  CoapplicantIncome  LoanAmount  \
Loan_Status Gender
N           Female               37                 37          36
            Male                150                150         140
Y           Female               75                 75          73
            Male                339                339         330

                    Loan_Amount_Term  Credit_History  Property_Area
Loan_Status Gender
N           Female                36              36             37
            Male                 145             138            150
Y           Female                73              65             75
            Male                 333             313            339

In [131]:
all_data = pd.concat([train_data,test_data],ignore_index=True)

In [132]:
all_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777.0,113.0,360.0,1.0,Urban,NaN
977,LP002975,Male,Yes,0,Graduate,No,4158,709.0,115.0,360.0,1.0,Urban,NaN
978,LP002980,Male,No,0,Graduate,No,3250,1993.0,126.0,360.0,NaN,Semiurban,NaN
979,LP002986,Male,Yes,0,Graduate,No,5000,2393.0,158.0,360.0,1.0,Rural,NaN
980,LP002989,Male,No,0,Graduate,Yes,9200,0.0,98.0,180.0,1.0,Rural,NaN

In [133]:
all_data['Credit_History']=all_data['Credit_History'].fillna(2)
#all_data['Credit_History']=all_data['Credit_History'].fillna(1)

In [134]:
all_data['Credit_History'].value_counts(dropna=False)

1.0    754
0.0    148
2.0     79
Name: Credit_History, dtype: int64

In [135]:
all_data['LoanAmount']=all_data['LoanAmount'].fillna(0)
#all_data['LoanAmount']=all_data['LoanAmount'].fillna(all_data['LoanAmount'].mean())

In [136]:
all_data['Loan_Amount_Term']=all_data['Loan_Amount_Term'].fillna(0)
#all_data['Loan_Amount_Term']=all_data['Loan_Amount_Term'].fillna(all_data['Loan_Amount_Term'].mean())

In [139]:
all_data['LoanAmount'].value_counts(dropna=False)

120.0    29
0.0      27
110.0    27
100.0    24
187.0    21
150.0    19
130.0    18
125.0    18
160.0    17
90.0     15
135.0    14
128.0    14
113.0    14
108.0    13
104.0    12
80.0     12
95.0     12
96.0     12
70.0     12
185.0    10
116.0    10
180.0    10
132.0    10
200.0    10
115.0    10
138.0    10
112.0     9
140.0     9
122.0     9
152.0     9
131.0     9
158.0     9
105.0     8
126.0     8
81.0      8
124.0     8
144.0     8
123.0     8
176.0     7
84.0      7
136.0     7
162.0     7
99.0      7
102.0     7
155.0     7
133.0     7
143.0     6
88.0      6
50.0      6
94.0      6
134.0     6
71.0      6
165.0     6
175.0     6
148.0     5
65.0      5
188.0     5
151.0     5
117.0     5
118.0     5
139.0     5
98.0      5
137.0     5
107.0     5
60.0      5
55.0      5
75.0      5
260.0     5
170.0     5
40.0      5
111.0     5
66.0      5
103.0     4
275.0     4
173.0     4
172.0     4
182.0     4
149.0     4
93.0      4
74.0      4
106.0     4
67.0      4
300.0     4
225.0     4
114.0     4
87.0      3
101.0     3
109.0     3
76.0      3
121.0     3
480.0     3
255.0     3
145.0     3
30.0      3
119.0     3
157.0     3
192.0     3
141.0     3
184.0     3
146.0     3
147.0     3
78.0      3
186.0     3
212.0     3
168.0     3
92.0      3
127.0     3
83.0      3
64.0      2
171.0     2
360.0     2
56.0      2
159.0     2
46.0      2
45.0      2
181.0     2
153.0     2
234.0     2
28.0      2
142.0     2
208.0     2
61.0      2
161.0     2
205.0     2
209.0     2
214.0     2
210.0     2
25.0      2
129.0     2
35.0      2
201.0     2
194.0     2
259.0     2
600.0     2
85.0      2
290.0     2
154.0     2
216.0     2
48.0      2
44.0      2
166.0     2
240.0     2
280.0     2
258.0     2
97.0      2
72.0      2
59.0      2
286.0     1
191.0     1
253.0     1
496.0     1
350.0     1
26.0      1
292.0     1
211.0     1
320.0     1
47.0      1
9.0       1
36.0      1
57.0      1
232.0     1
315.0     1
189.0     1
254.0     1
183.0     1
68.0      1
177.0     1
297.0     1
460.0     1
49.0      1
267.0     1
349.0     1
17.0      1
412.0     1
336.0     1
235.0     1
79.0      1
199.0     1
550.0     1
213.0     1
256.0     1
390.0     1
77.0      1
257.0     1
163.0     1
196.0     1
324.0     1
279.0     1
312.0     1
296.0     1
570.0     1
236.0     1
308.0     1
228.0     1
63.0      1
490.0     1
700.0     1
495.0     1
376.0     1
73.0      1
58.0      1
164.0     1
89.0      1
54.0      1
436.0     1
207.0     1
42.0      1
330.0     1
304.0     1
380.0     1
156.0     1
400.0     1
244.0     1
311.0     1
250.0     1
167.0     1
243.0     1
265.0     1
500.0     1
246.0     1
86.0      1
230.0     1
370.0     1
190.0     1
650.0     1
405.0     1
239.0     1
178.0     1
218.0     1
62.0      1
53.0      1
242.0     1
197.0     1
Name: LoanAmount, dtype: int64

In [140]:
all_data['Credit_History'].value_counts(dropna=False)

1.0    754
0.0    148
2.0     79
Name: Credit_History, dtype: int64

In [141]:
all_data['Gender'].value_counts(dropna=False)

Male      775
Female    182
NaN        24
Name: Gender, dtype: int64

In [142]:
all_data['Gender'].fillna('Unknown',inplace=True)

In [143]:
all_data['Gender'].value_counts(dropna=False)

Male       775
Female     182
Unknown     24
Name: Gender, dtype: int64

In [144]:
all_data['Married'].fillna('Unkown',inplace=True)

In [145]:
all_data['Married'].value_counts(dropna=False)

Yes       631
No        347
Unkown      3
Name: Married, dtype: int64

In [146]:
all_data['Self_Employed'].fillna('Unkown',inplace=True)

In [147]:
all_data['Self_Employed'].value_counts(dropna=False)

No        807
Yes       119
Unkown     55
Name: Self_Employed, dtype: int64

In [148]:
#all_data['Dependents'] = all_data['Dependents'].astype(int)
all_data['Dependents'].value_counts(dropna=False)

0      545
1      160
2      160
3+      91
NaN     25
Name: Dependents, dtype: int64

In [149]:
all_data['Dependents'].fillna('Unkown',inplace=True)

In [150]:
all_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,0.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777.0,113.0,360.0,1.0,Urban,NaN
977,LP002975,Male,Yes,0,Graduate,No,4158,709.0,115.0,360.0,1.0,Urban,NaN
978,LP002980,Male,No,0,Graduate,No,3250,1993.0,126.0,360.0,2.0,Semiurban,NaN
979,LP002986,Male,Yes,0,Graduate,No,5000,2393.0,158.0,360.0,1.0,Rural,NaN
980,LP002989,Male,No,0,Graduate,Yes,9200,0.0,98.0,180.0,1.0,Rural,NaN

In [151]:
all_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Loan_ID,981,981,LP001002,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,981,3,Male,775,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Married,981,3,Yes,631,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,981,5,0,545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education,981,2,Graduate,763,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Self_Employed,981,3,No,807,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ApplicantIncome,981.0,NaN,NaN,NaN,5179.795107,5695.104533,0.0,2875.0,3800.0,5516.0,81000.0
CoapplicantIncome,981.0,NaN,NaN,NaN,1601.91633,2718.772806,0.0,0.0,1110.0,2365.0,41667.0
LoanAmount,981.0,NaN,NaN,NaN,138.589195,79.831886,0.0,99.0,125.0,160.0,700.0
Loan_Amount_Term,981.0,NaN,NaN,NaN,335.22528,80.577376,0.0,360.0,360.0,360.0,480.0
Credit_History,981.0,NaN,NaN,NaN,0.929664,0.47611,0.0,1.0,1.0,1.0,2.0
Property_Area,981,3,Semiurban,349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Loan_Status,614,2,Y,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [152]:
all_data = pd.get_dummies(all_data,columns=['Gender','Married','Dependents','Education','Property_Area','Self_Employed','Credit_History'])
#all_data = pd.get_dummies(all_data,columns=['Gender','Married','Dependents','Education','Property_Area','Self_Employed'])

In [153]:
all_data

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Loan_Status,Gender_Female,Gender_Male,Gender_Unknown,Married_No,...,Education_Not Graduate,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Self_Employed_No,Self_Employed_Unkown,Self_Employed_Yes,Credit_History_0.0,Credit_History_1.0,Credit_History_2.0
0,LP001002,5849,0.0,0.0,360.0,Y,0,1,0,1,...,0,0,0,1,1,0,0,0,1,0
1,LP001003,4583,1508.0,128.0,360.0,N,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
2,LP001005,3000,0.0,66.0,360.0,Y,0,1,0,0,...,0,0,0,1,0,0,1,0,1,0
3,LP001006,2583,2358.0,120.0,360.0,Y,0,1,0,0,...,1,0,0,1,1,0,0,0,1,0
4,LP001008,6000,0.0,141.0,360.0,Y,0,1,0,1,...,0,0,0,1,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,LP002971,4009,1777.0,113.0,360.0,NaN,0,1,0,0,...,1,0,0,1,0,0,1,0,1,0
977,LP002975,4158,709.0,115.0,360.0,NaN,0,1,0,0,...,0,0,0,1,1,0,0,0,1,0
978,LP002980,3250,1993.0,126.0,360.0,NaN,0,1,0,1,...,0,0,1,0,1,0,0,0,0,1
979,LP002986,5000,2393.0,158.0,360.0,NaN,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
980,LP002989,9200,0.0,98.0,180.0,NaN,0,1,0,1,...,0,1,0,0,0,0,1,0,1,0

In [154]:
all_data.drop(columns=['Loan_ID']).corr()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Gender_Female,Gender_Male,Gender_Unknown,Married_No,Married_Unkown,Married_Yes,...,Education_Not Graduate,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Self_Employed_No,Self_Employed_Unkown,Self_Employed_Yes,Credit_History_0.0,Credit_History_1.0,Credit_History_2.0
ApplicantIncome,1.000000,-0.114247,0.518314,-0.006297,-0.060444,0.026282,0.082797,-0.052126,0.009995,0.050873,...,-0.138909,-0.000099,-0.009034,0.009171,-0.108873,0.020259,0.113106,-0.020201,0.029453,-0.019076
CoapplicantIncome,-0.114247,1.000000,0.178831,-0.049129,-0.082428,0.081674,-0.007926,-0.061606,-0.027527,0.064660,...,-0.060380,0.035925,-0.026793,-0.007484,-0.015080,0.051807,-0.018861,0.011531,-0.068562,0.091090
LoanAmount,0.518314,0.178831,1.000000,0.058462,-0.087561,0.061332,0.058620,-0.140185,-0.022621,0.142522,...,-0.163894,0.037799,0.002358,-0.038565,-0.104833,0.026745,0.103809,-0.001292,-0.023243,0.037722
Loan_Amount_Term,-0.006297,-0.049129,0.058462,1.000000,0.063592,-0.066117,0.014305,0.048255,0.017038,-0.050126,...,-0.056236,0.014941,0.054579,-0.069140,0.026946,-0.017463,-0.019222,-0.033501,0.019032,0.014569
Gender_Female,-0.060444,-0.082428,-0.087561,0.063592,1.000000,-0.925720,-0.075581,0.327012,0.021060,-0.328808,...,-0.040649,-0.067824,0.094498,-0.029989,0.015662,0.009075,-0.024719,0.018627,-0.030381,0.022585
Gender_Male,0.026282,0.081674,0.061332,-0.066117,-0.925720,1.000000,-0.307162,-0.325238,-0.016772,0.326543,...,0.040802,0.065251,-0.103057,0.041052,-0.003526,0.005977,-0.000086,-0.027421,0.031645,-0.012976
Gender_Unknown,0.082797,-0.007926,0.058620,0.014305,-0.075581,-0.307162,1.000000,0.034649,-0.008771,-0.033571,...,-0.005290,-0.001371,0.033930,-0.032775,-0.030111,-0.038595,0.062424,0.025426,-0.006986,-0.022617
Married_No,-0.052126,-0.061606,-0.140185,0.048255,0.327012,-0.325238,0.034649,1.000000,-0.040974,-0.993346,...,-0.026211,0.001967,0.006909,-0.008825,0.003055,0.014322,-0.013666,0.021738,-0.018733,0.000439
Married_Unkown,0.009995,-0.027527,-0.022621,0.017038,0.021060,-0.016772,-0.008771,-0.040974,1.000000,-0.074366,...,-0.029604,-0.035880,0.035968,-0.001777,0.025718,-0.013498,-0.020578,-0.023345,0.030389,-0.016391
Married_Yes,0.050873,0.064660,0.142522,-0.050126,-0.328808,0.326543,-0.033571,-0.993346,-0.074366,1.000000,...,0.029573,0.002172,-0.011042,0.009013,-0.006014,-0.012739,0.016012,-0.019005,0.015194,0.001451
Dependents_0,-0.093017,0.007614,-0.111045,0.039386,0.115516,-0.113605,0.008853,0.357073,-0.061922,-0.349247,...,-0.054827,0.048952,-0.008094,-0.038744,0.062656,-0.040624,-0.044683,-0.024200,0.019998,0.000838
Dependents_1,0.027478,-0.007011,0.028760,-0.033164,0.016439,-0.009495,-0.016330,-0.118849,-0.024450,0.121438,...,-0.023597,-0.050177,0.017742,0.030225,-0.076715,0.060323,0.047252,-0.031904,0.013238,0.021447
Dependents_2,-0.021144,0.018375,0.056631,0.030969,-0.118421,0.125988,-0.034190,-0.245805,-0.024450,0.248148,...,0.042769,0.022380,-0.028364,0.007065,-0.018930,0.012348,0.013448,0.006640,0.013238,-0.029251
Dependents_3+,0.150853,-0.008810,0.114340,-0.058705,-0.071256,0.052704,0.040343,-0.148371,-0.017710,0.150126,...,0.074190,-0.014639,0.011934,0.002029,0.001294,-0.001557,-0.000417,0.061567,-0.057849,0.008675
Dependents_Unkown,0.000748,-0.034432,-0.060535,-0.010974,0.006022,-0.011915,0.016262,0.002124,0.342492,-0.041596,...,-0.008644,-0.062235,0.028455,0.031008,0.024288,-0.039411,-0.000646,0.022199,-0.018637,-0.000315
Education_Graduate,0.138909,0.060380,0.163894,0.056236,0.040649,-0.040802,0.005290,0.026211,0.029604,-0.029573,...,-1.000000,-0.051345,0.013089,0.036017,-0.010698,0.002369,0.010848,-0.062416,0.055557,-0.004005
Education_Not Graduate,-0.138909,-0.060380,-0.163894,-0.056236,-0.040649,0.040802,-0.005290,-0.026211,-0.029604,0.029573,...,1.000000,0.051345,-0.013089,-0.036017,0.010698,-0.002369,-0.010848,0.062416,-0.055557,0.004005
Property_Area_Rural,-0.000099,0.035925,0.037799,0.014941,-0.067824,0.065251,-0.001371,0.001967,-0.035880,0.002172,...,0.051345,1.000000,-0.481409,-0.473939,-0.061772,0.016907,0.060360,0.026518,-0.015335,-0.011113
Property_Area_Semiurban,-0.009034,-0.026793,0.002358,0.054579,0.094498,-0.103057,0.033930,0.006909,0.035968,-0.011042,...,-0.013089,-0.481409,1.000000,-0.543647,0.027326,-0.023757,-0.015231,-0.009830,0.013922,-0.008647
Property_Area_Urban,0.009171,-0.007484,-0.038565,-0.069140,-0.029989,0.041052,-0.032775,-0.008825,-0.001777,0.009013,...,-0.036017,-0.473939,-0.543647,1.000000,0.031700,0.007678,-0.042498,-0.015517,0.000698,0.019328
Self_Employed_No,-0.108873,-0.015080,-0.104833,0.026946,0.015662,-0.003526,-0.030111,0.003055,0.025718,-0.006014,...,0.010698,-0.061772,0.027326,0.031700,1.000000,-0.524853,-0.800169,0.016782,-0.001664,-0.019494
Self_Employed_Unkown,0.020259,0.051807,0.026745,-0.017463,0.009075,0.005977,-0.038595,0.014322,-0.013498,-0.012739,...,-0.002369,0.016907,-0.023757,0.007678,-0.524853,1.000000,-0.090552,0.021075,-0.044899,0.041864
Self_Employed_Yes,0.113106,-0.018861,0.103809,-0.019222,-0.024719,-0.000086,0.062424,-0.013666,-0.020578,0.016012,...,-0.010848,0.060360,-0.015231,-0.042498,-0.800169,-0.090552,1.000000,-0.034485,0.033584,-0.006690
Credit_History_0.0,-0.020201,0.011531,-0.001292,-0.033501,0.018627,-0.027421,0.025426,0.021738,-0.023345,-0.019005,...,0.062416,0.026518,-0.009830,-0.015517,0.016782,0.021075,-0.034485,1.000000,-0.768212,-0.124744
Credit_History_1.0,0.029453,-0.068562,-0.023243,0.019032,-0.030381,0.031645,-0.006986,-0.018733,0.030389,0.015194,...,-0.055557,-0.015335,0.013922,0.000698,-0.001664,-0.044899,0.033584,-0.768212,1.000000,-0.539365
Credit_History_2.0,-0.019076,0.091090,0.037722,0.014569,0.022585,-0.012976,-0.022617,0.000439,-0.016391,0.001451,...,0.004005,-0.011113,-0.008647,0.019328,-0.019494,0.041864,-0.006690,-0.124744,-0.539365,1.000000

In [155]:
all_data.describe().T

,count,mean,std,min,25%,50%,75%,max
ApplicantIncome,981.0,5179.795107,5695.104533,0.0,2875.0,3800.0,5516.0,81000.0
CoapplicantIncome,981.0,1601.916330,2718.772806,0.0,0.0,1110.0,2365.0,41667.0
LoanAmount,981.0,138.589195,79.831886,0.0,99.0,125.0,160.0,700.0
Loan_Amount_Term,981.0,335.225280,80.577376,0.0,360.0,360.0,360.0,480.0
Gender_Female,981.0,0.185525,0.388921,0.0,0.0,0.0,0.0,1.0
Gender_Male,981.0,0.790010,0.407509,0.0,1.0,1.0,1.0,1.0
Gender_Unknown,981.0,0.024465,0.154566,0.0,0.0,0.0,0.0,1.0
Married_No,981.0,0.353721,0.478368,0.0,0.0,0.0,1.0,1.0
Married_Unkown,981.0,0.003058,0.055244,0.0,0.0,0.0,0.0,1.0
Married_Yes,981.0,0.643221,0.479293,0.0,0.0,1.0,1.0,1.0
Dependents_0,981.0,0.555556,0.497157,0.0,0.0,1.0,1.0,1.0
Dependents_1,981.0,0.163099,0.369644,0.0,0.0,0.0,0.0,1.0
Dependents_2,981.0,0.163099,0.369644,0.0,0.0,0.0,0.0,1.0
Dependents_3+,981.0,0.092762,0.290247,0.0,0.0,0.0,0.0,1.0
Dependents_Unkown,981.0,0.025484,0.157671,0.0,0.0,0.0,0.0,1.0
Education_Graduate,981.0,0.777778,0.415952,0.0,1.0,1.0,1.0,1.0
Education_Not Graduate,981.0,0.222222,0.415952,0.0,0.0,0.0,0.0,1.0
Property_Area_Rural,981.0,0.295617,0.456552,0.0,0.0,0.0,1.0,1.0
Property_Area_Semiurban,981.0,0.355759,0.478987,0.0,0.0,0.0,1.0,1.0
Property_Area_Urban,981.0,0.348624,0.476778,0.0,0.0,0.0,1.0,1.0
Self_Employed_No,981.0,0.822630,0.382176,0.0,1.0,1.0,1.0,1.0
Self_Employed_Unkown,981.0,0.056065,0.230165,0.0,0.0,0.0,0.0,1.0
Self_Employed_Yes,981.0,0.121305,0.326648,0.0,0.0,0.0,0.0,1.0
Credit_History_0.0,981.0,0.150866,0.358101,0.0,0.0,0.0,0.0,1.0
Credit_History_1.0,981.0,0.768603,0.421940,0.0,1.0,1.0,1.0,1.0
Credit_History_2.0,981.0,0.080530,0.272251,0.0,0.0,0.0,0.0,1.0

### Feature Selection:

In [156]:
pp_train = all_data[all_data['Loan_Status'].notna()]
pp_test = all_data[all_data['Loan_Status'].isna()]

#pp_train = preprocessed_data[preprocessed_data['Loan_Status'].notna()]
#pp_test = preprocessed_data[preprocessed_data['Loan_Status'].isna()]

In [157]:
pp_train.shape

(614, 28)

In [158]:
pp_test.shape

(367, 28)

In [159]:
pp_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 614 entries, 0 to 613
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Loan_ID                  614 non-null    object
 1   ApplicantIncome          614 non-null    int64
 2   CoapplicantIncome        614 non-null    float64
 3   LoanAmount               614 non-null    float64
 4   Loan_Amount_Term         614 non-null    float64
 5   Loan_Status              614 non-null    object
 6   Gender_Female            614 non-null    uint8
 7   Gender_Male              614 non-null    uint8
 8   Gender_Unknown           614 non-null    uint8
 9   Married_No               614 non-null    uint8
 10  Married_Unkown           614 non-null    uint8
 11  Married_Yes              614 non-null    uint8
 12  Dependents_0             614 non-null    uint8
 13  Dependents_1             614 non-null    uint8
 14  Dependents_2             614 non-null    uint8
 15  Dependents_3+            614 non-null    uint8
 16  Dependents_Unkown        614 non-null    uint8
 17  Education_Graduate       614 non-null    uint8
 18  Education_Not Graduate   614 non-null    uint8
 19  Property_Area_Rural      614 non-null    uint8
 20  Property_Area_Semiurban  614 non-null    uint8
 21  Property_Area_Urban      614 non-null    uint8
 22  Self_Employed_No         614 non-null    uint8
 23  Self_Employed_Unkown     614 non-null    uint8
 24  Self_Employed_Yes        614 non-null    uint8
 25  Credit_History_0.0       614 non-null    uint8
 26  Credit_History_1.0       614 non-null    uint8
 27  Credit_History_2.0       614 non-null    uint8
dtypes: float64(3), int64(1), object(2), uint8(22)
memory usage: 46.8+ KB

In [160]:
X = pp_train.drop(columns=['Loan_ID','Loan_Status'])
y = pp_train['Loan_Status']

In [195]:
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size=0.2,random_state=42)
train_X.shape, test_X.shape, train_y.shape, test_y.shape

((491, 26), (123, 26), (491,), (123,))

In [196]:
train_X.shape[0], test_X.shape[0], train_X.shape[0]+ test_X.shape[0], pp_train.shape[0]

(491, 123, 614, 614)

In [197]:
train_y.isna().sum()

0

### Model Creation:

In [198]:
model = LogisticRegression(max_iter=500)
model.fit(train_X,train_y)

LogisticRegression(max_iter=500)

In [199]:
model.coef_, model.intercept_

(array([[-1.69712961e-05, -6.30971065e-05, -6.22729188e-04,
         -2.11995798e-03, -1.28470241e-02,  2.49606105e-01,
         -4.35543211e-02, -3.38066399e-01,  1.25995312e-02,
          5.18671628e-01,  1.50192762e-01, -1.17440448e-01,
          1.99867545e-01,  3.87906778e-02, -7.82057775e-02,
          3.08723850e-01, -1.15519090e-01, -2.88376529e-01,
          5.86523901e-01, -1.04942612e-01,  9.19894218e-02,
          5.72864345e-02,  4.39289035e-02, -1.34090327e+00,
          1.41471733e+00,  1.19390698e-01]]),
 array([0.19320539]))

In [200]:
y_pred = model.predict(train_X)
print('Train accuracy')
print('accuracy score',accuracy_score(train_y,y_pred))
print('f1 score',f1_score(train_y,y_pred,pos_label='Y'))
print('confusion matrix\n',confusion_matrix(train_y,y_pred))

Train accuracy
accuracy score 0.7983706720977597
f1 score 0.8671140939597315
confusion matrix
 [[ 69  80]
 [ 19 323]]

In [201]:
y_test_pred = model.predict(test_X)
print('Test accuracy')
print('accuracy score',accuracy_score(test_y,y_test_pred))
print('f1 score',f1_score(test_y,y_test_pred,pos_label='Y'))
print('confusion matrix\n',confusion_matrix(test_y,y_test_pred))

Test accuracy
accuracy score 0.7804878048780488
f1 score 0.8508287292817679
confusion matrix
 [[19 24]
 [ 3 77]]

### Model Deployment:

In [202]:
pptest_X = pp_test.drop(columns=['Loan_ID','Loan_Status'])
y_unpred = model.predict(pptest_X)

In [203]:
np.unique(y_unpred, return_counts=True)

(array(['N', 'Y'], dtype=object), array([ 69, 298], dtype=int64))

In [204]:
sample_data['Loan_Status']=y_unpred
sample_data['Loan_Status']=sample_data['Loan_Status']
sample_data.to_csv('submission_loan_prd_lr1.csv',index=False)